#!/usr/bin/env sh

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 9 --label nine

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^licecap$" sticky=on layer=above manage=off
yabai -m rule --add app="^Chromium$" space=1 sticky=on layer=above manage=off

# float all JetBrains apps
apps='^(IntelliJ IDEA|WebStorm|CLion|JetBrains Rider)$'
yabai -m rule --add app="${apps}" manage=on

# add a signal that floats a window created by these apps when it's the only window
yabai -m signal --add event=window_created app="${apps}" action='~/bashscripts/yabai/ignore-app-sub-windows.sh'

# New window spawns to the left if vertical split, or top if horizontal split
yabai -m config window_placement first_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config layout bsp
yabai -m config --space 1 layout stack
yabai -m config top_padding 20
yabai -m config bottom_padding 50
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="bash /Users/kolacampell/bashscripts/yabai/window-focus-on-destroy.sh"

echo "yabai configuration loaded.."
#END
