require("nvim-lsp-installer").setup({})
require("kola.lsp.servers.null-ls")
--require("kola.lsp.servers.jsonls")
require("kola.lsp.servers.deno")
require("kola.lsp.servers.tsserver")
require("kola.lsp.servers.sumneko")
require("kola.lsp.servers.omnisharp")
require("kola.lsp.handlers")
