palette = "catppuccin_mocha"
command_timeout = 1000
format = """
$directory\
[](fg:#f38ba8 bg:#a6e3a1)\
$git_branch\
$git_status\
[](fg:#a6e3a1 bg:#a6e3a1)\
[ ](fg:#a6e3a1)
$character"""

[character] # The name of the module we are configuring is "character"
success_symbol = "[\\$](bold green)" 
error_symbol = "[\\$](bold red)" 

# Disable the blank line at the start of the prompt
# add_newline = false

[directory]
style = "bg:#f38ba8 fg:#1e1e2e"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[[ $symbol $branch ](bg:#a6e3a1 fg:#1e1e2e)]($style)'

[git_status]
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[[($conflicted$deleted$renamed$modified$staged$untracked$ahead_behind )](bg:#a6e3a1 fg:#1e1e2e)]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
