command_timeout = 1000
format = """
$directory\
[](fg:#D16969 bg:#608B4E)\
$git_branch\
$git_status\
[](fg:#608B4E bg:#608B4E)\
[ ](fg:#608B4E)
$character"""

[character] # The name of the module we are configuring is "character"
success_symbol = "[\\$](bold green)" 
error_symbol = "[\\$](bold red)" 

# Disable the blank line at the start of the prompt
# add_newline = false

[directory]
style = "bg:#D16969 fg:black"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#608B4E fg:black"
format = '[[ $symbol $branch ](bg:#608B4E fg:black)]($style)'

[git_status]
style = "bg:#608B4E fg:black"
format = '[[($conflicted$deleted$renamed$modified$staged$untracked$ahead_behind )](bg:#608B4E fg:black)]($style)'
